### ISSUE TITLE
Opening newComment template with suggestion elements visible when includeSuggestion is not selected

### ISSUE THREAD

**Issue by lpagliari** [JohnMcLear/ep_comments#34]
To reproduce:

1. click the button to add a comment;
2. click on Cancel, instead of creating the comment;
3. click the button to add a comment again;
4. the form will be opened with suggestion elements visible:

![image](https://cloud.githubusercontent.com/assets/836386/7773098/95420f1e-0078-11e5-81af-6eb8851e1c62.png)

Seems to be an easy fix. I can work on it after I'm done with l10n, if you want.

**Comment by JohnMcLear** [comment]
Yes please that would be useful!

On 22 May 2015 15:52, Luiza Pagliari <notifications@github.com> wrote:

To reproduce:

  1.  click the button to add a comment;
  2.  click on Cancel, instead of creating the comment;
  3.  click the button to add a comment again;
  4.  the form will be opened with suggestion elements visible:

[image]<https://cloud.githubusercontent.com/assets/836386/7773098/95420f1e-0078-11e5-81af-6eb8851e1c62.png>

Seems to be an easy fix. I can work on it after I'm done with l10n, if you want.

**Comment by JohnMcLear** [comment]
Ah just doing a git pull should have this fixed.
