### ISSUE TITLE
Feature suggestion: Display comments as icons on right margin

### ISSUE THREAD

**Issue by lpagliari** [JohnMcLear/ep_comments#36]
On the Etherpad instance we're using, we need another way to display comments. I don't know if it would be useful for ep_comments to have it incorporated to the code, or if we should implement it on a separated plugin (or a fork of this one). Let me know if you think this is something nice to have here, and I'll submit a PR.

Here are the details about it:

* Instead of displaying boxes on the right side of the screen, there would be icons on the right margin of the page:

  ![image](https://cloud.githubusercontent.com/assets/836386/7888103/725ecc28-060c-11e5-883d-0881d3944135.png)

* Comment details would be displayed only when I click on the icon:

  ![image](https://cloud.githubusercontent.com/assets/836386/7888131/a49fbca6-060c-11e5-9ba6-0a6b314a01e1.png)

* Clicking again on the icon would close comment details;
* Comments with replies would have a different icon (the actual icon I was thinking is [this one](http://fortawesome.github.io/Font-Awesome/icon/comments-o/), but I could not find it quickly on Etherpad, so I used the ones I found for this spike):

  ![image](https://cloud.githubusercontent.com/assets/836386/7888149/c29ff8ec-060c-11e5-9d54-9283630514cb.png)

* When there are 2+ comments on the same line, each comment would have its own icon, side-by-side:

  ![image](https://cloud.githubusercontent.com/assets/836386/7888179/f38eb736-060c-11e5-8852-fde1a90086d1.png)

* One thing that we can do is create a toggle to allow user to choose whether to display comments as icons or as it is right now.

Let me know your thoughts.

**Comment by JohnMcLear** [comment]
Do it in the main branch but put it under a server side setting called "onlyShowCommentIcon" or something :). Its a good suggestion BTW as it keeps ui clean

On 29 May 2015 18:17, Luiza Pagliari <notifications@github.com> wrote:

On the Etherpad instance we're using, we need another way to display comments. I don't know if it would be useful for ep_comments to have it incorporated to the code, or if we should implement it on a separated plugin (or a fork of this one). Let me know if you think this is something nice to have here, and I'll submit a PR.

Here are the details about it:

  *   Instead of displaying boxes on the right side of the screen, there would be icons on the right margin of the page:

[image]<https://cloud.githubusercontent.com/assets/836386/7888103/725ecc28-060c-11e5-883d-0881d3944135.png>

  *   Comment details would be displayed only when I click on the icon:

[image]<https://cloud.githubusercontent.com/assets/836386/7888131/a49fbca6-060c-11e5-9ba6-0a6b314a01e1.png>

  *   Clicking again on the icon would close comment details;

  *   Comments with replies would have a different icon:

[image]<https://cloud.githubusercontent.com/assets/836386/7888149/c29ff8ec-060c-11e5-9d54-9283630514cb.png>

  *   When there are 2+ comments on the same line, each comment would have its own icon, side-by-side:

[image]<https://cloud.githubusercontent.com/assets/836386/7888179/f38eb736-060c-11e5-8852-fde1a90086d1.png>

  *   One thing that we can do is create a toggle to allow user to choose whether to display comments as icons or as it is right now.

Let me know your thoughts.

**Comment by lpagliari** [comment]
Awesome, thanks!

**Comment by JohnMcLear** [comment]
Quick question, does this introduce another http request?

**Comment by lpagliari** [comment]
Nope, it just handles what comes on the inner pad (the comment ids), in a
very similar way of what is done with sidebar comments.

**Comment by JohnMcLear** [comment]
I put this live on https://beta.etherpad.org/p/HAKOOKy48b so it gets some testing..

Some thing I noticed..

1) It looks kinda bad when page view isn't on

2) Icons don't look right still?

**Comment by lpagliari** [comment]
Still working on that. I finished my fixes for the icons when PV is off some minutes ago, but had to rebase and now I'm checking if something is broken after the last 30+ commits we had on the last few days. :)

**Comment by JohnMcLear** [comment]
Yeah sorry about that..  I'm done now =)

**Comment by lpagliari** [comment]
no, no, it was awesome!! Great features, I loved it

**Comment by lpagliari** [comment]
ok, submitted PR #57 now.

**Comment by JohnMcLear** [comment]
Updated beta.etherpad.org still getting that issue.  Maybe it should be forcing page view on too?

**Comment by lpagliari** [comment]
Hum, it looks fine for me when PV is off:

![image](https://cloud.githubusercontent.com/assets/836386/8217108/892520b0-1511-11e5-8698-307019ba4d6d.png)

**Comment by JohnMcLear** [comment]
![image](http://i.imgur.com/WymcdOO.png)

**Comment by lpagliari** [comment]
This is the icon I added to Etherpad code a few days ago. Is beta.etherpad.org using the `develop` branch?

**Comment by JohnMcLear** [comment]
blah good point I don't think I pulled the repo, sec..

**Comment by JohnMcLear** [comment]
There ya go, looking sexy!

Good job!

**Comment by lpagliari** [comment]
:)
